### ISSUE TITLE
Robot Upstart unable to find the turtlebot4.service

### ISSUE THREAD

**Issue by sumitpaulde** [turtlebot/turtlebot4_setup#8]
- OS: Ubuntu 22.04
 - ROS Distro:  Humble
 - Built from source 

 **Expected behaviour**
Robot startup should work.

 **Actual behaviour**
When I try to start the Robot Upstart from the ROS Setup, I get this error. There is no service named as turtlebot4.service

```
failed to stop turtlebot4.service: Unit turtlebot4.service not loaded.
Traceback (most recent call last):
  File "/opt/ros/humble/lib/turtlebot4_setup/turtlebot4_setup", line 246, in <module>
    main()
  File "/opt/ros/humble/lib/turtlebot4_setup/turtlebot4_setup", line 242, in main
    setup.run()
  File "/opt/ros/humble/lib/turtlebot4_setup/turtlebot4_setup", line 186, in run
    self.menu.show()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/turtlebot4_setup/menu.py", line 95, in show
    self.menu_entries[self.menu_sel].select()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/turtlebot4_setup/menu.py", line 29, in select
    self.function()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/turtlebot4_setup/ros_setup.py", line 37, in show
    self.menu.show()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/turtlebot4_setup/menu.py", line 95, in show
    self.menu_entries[self.menu_sel].select()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/turtlebot4_setup/menu.py", line 29, in select
    self.function()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/turtlebot4_setup/ros_setup.py", line 244, in show
    self.menu.show()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/turtlebot4_setup/menu.py", line 95, in show
    self.menu_entries[self.menu_sel].select()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/turtlebot4_setup/menu.py", line 29, in select
    self.function()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/turtlebot4_setup/ros_setup.py", line 265, in install
    self.uninstall()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/turtlebot4_setup/ros_setup.py", line 297, in uninstall
    workspace_setup=os.environ['ROBOT_SETUP'])
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'ROBOT_SETUP'
[ros2run]: Process exited with failure 1

```

**To Reproduce**
Take a fresh sd card follow the instructions to build the turtlebot4 from the source for Humble.

**Comment by roni-kreinin** [comment]
@sumitpaulde Is the `$ROBOT_SETUP` environment variable defined in `~/.bashrc`?

See https://github.com/turtlebot/turtlebot4_setup/blob/d499511be43fc85091d9bd25a809cff1167dd7c6/scripts/turtlebot4_setup.sh#L56

**Comment by sumitpaulde** [comment]
Hi @roni-kreinin 

The path for me was different and I had to change the path in the bashrc. After that I faced another error
```
Dec 07 11:44:20 ubuntu turtlebot4-start[2368]: ls: cannot access '/etc/ros/humble/turtlebot4.d/*.xacro': No such file or directory
```
I had to install 
```
sudo apt install ros-humble-xacro
```
Now the Robot Startup works.
